language: c

env:
  - CTEST_OUTPUT_ON_FAILURE=1

arch:
  - arm64
  - amd64

before_install:
 - export LD_LIBRARY_PATH=$(if [[ $CC == "clang" ]]; then echo -n '/usr/local/clang/lib'; fi)

compiler:
  - clang
  - gcc

script:
  - ./configure --devel --debug --test && make && make test 
  - ./configure --devel --test && make && make test 
