language: c

env:
  - CTEST_OUTPUT_ON_FAILURE=1

arch:
  - arm64
  - amd64

compiler:
  - clang
  - gcc

script:
  - ./configure --devel --debug --test && make && make test 
  - ./configure --devel --test && make && make test 
